name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: xcodebuild -project GPTravel.xcodeproj -scheme GPTravel -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO
